server:
  port: 8080

spring:
  application:
    name: individuals-api
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8180/realms/${keycloak.realm}
        registration:
          keycloak:
            client-id: app-auth-client-id
            client-secret: "**********"
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/${keycloak.realm}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
keycloak:
  server-url: http://localhost:8180
  realm: appauth
  username: admin
  password: adminpass

logging:
  level:
    org.springframework.web: INFO







