server:
  port: 8080

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/keycloak_authenticator
    username: postgres
    password: root
    pool:
      initial-size: 1
      max-size: 10
      max-idle-time: 30m
  flyway:
    url: jdbc:postgresql://localhost:5432/keycloak_authenticator
    locations: classpath:db/migration
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8180/realms/myrealm
        registration:
          keycloak:
            client-id: my-client
            client-secret: oG4nqOAEvbllPJ4XOYK06KID3m1wiW8u
keycloak:
  server-url: http://localhost:8180
  realm: myrealm
  username: admin
  password: adminpass

logging:
  level:
    org.springframework.web: INFO

---
spring:
  config:
    activate:
      on-profile: test
  r2dbc:
    url: r2dbc:tc:postgresql:///integration_test_db?TC_IMAGE_TAG=14-alpine






